### ISSUE TITLE
[Question] memory leaks or GC not kicking in or it just php?

### ISSUE THREAD

**Issue by attozk** [igorw/evenement#24]
Trying to figure out why PHP doesn't free up memory for evenement @ https://gist.github.com/attozk/e77987fd01488db836b6

I have let the script run for a long time and it still doesn't free up memory. In other cases I have ran out of memory.

**Comment by WyriHaximus** [comment]
This could be related to #32, currently looking into that pull request

**Comment by WyriHaximus** [comment]
Merged in #32 that should free up the unused memory for longer running evenement instances.
