### ISSUE TITLE
Does somebody maintains this package?

### ISSUE THREAD

**Issue by Nayjest** [igorw/evenement#28]
@igorw has no github activity last 8 months. Does somebody maintain this package?

**Comment by JCMais** [comment]
The project is mostly dead, I'm using https://github.com/fruux/sabre-event now.

**Comment by Nayjest** [comment]
@JCMais  maybe it's not active becouse code by @igorw is very simple and almost ideal. 
On other side,  https://github.com/fruux/sabre-event contais ugly shit that must be moved to some another lib becouse it solves another problems (Promises, etc).

**Comment by Nayjest** [comment]
I found some presentations by @igorw on speakerdeck dated 2015, so I can conclude that this package mantainer is alive and still programs therefore I'm closing issue.
