### ISSUE TITLE
Event namespace support

### ISSUE THREAD

**Issue by shtse8** [igorw/evenement#50]
Something like https://api.jquery.com/event.namespace/
For excample, we want to listen on `statusChanged` event buy only for value `idle`. We can code like that:

Listeners:
```
$this->once("statusChanged.idle", function() {
    echo "The status is changed to idle.\n";
});
$this->on("statusChanged", function() {
   echo "The status is changed.\n";
});
```
the emitter 
```
$this->emit("statusChange.idle");
$this->emit("statusChange.idle");
```
Result:
```
The status is changed to idle
The status is changed.
The status is changed.
```

instead of
```
$this->on("statusChanged", function($status) {
   echo "The status is changed.\n";
});
$onceListener = function($status) use (&$onceListener ) {
   if ($status == "idle") {
        echo "The status is changed to idle.\n";
        $this->removeListener("statusChanged", $onceListener);
    }
};
$this->on("statusChanged", $onceListener );
$this->emit("statusChange", ['idle']);
```

The main advantage that we can easily use it with `once`.

**Comment by WyriHaximus** [comment]
While this sounds interesting, my main concern is performance. A performance hit isn't really an option tbh.

**Comment by WyriHaximus** [comment]
While revisiting all the issues for this package. This feature would introduce too big of a performance hit and is also beyond the scope of this package.
