### ISSUE TITLE
Adding a 'once' listener inside an 'on' handler for the same event will immediately trigger the 'once' with that event

### ISSUE THREAD

**Issue by dpbricher** [igorw/evenement#62]
macOS High Sierra 10.13.4
PHP 7.0.31 (cli) (built: Jul 19 2018 23:41:03) ( NTS )

Running this code:
```php
$emitter  = new Evenement\EventEmitter();

$emitter->on('A', function() use (&$emitter) {
  print("Original A call\n");

  $emitter
    ->on('A', function() {
      print("Nested A call\n");
    })
    ->once('A', function() {
      print("Nested A ONCE call\n");
    });
});

$emitter->emit('A');
```

Produces the following output:
> Original A call  
  Nested A ONCE call

But I think the expected result should be:
> Original A call

**Comment by battlecook** [comment]
I agree with it

**Comment by WyriHaximus** [comment]
@battlecook thank you for your PR's, will have a look at them somewhere this week 👍 .

**Comment by WyriHaximus** [comment]
This has been merged some years ago and will be released later today.
