### ISSUE TITLE
Define behavior for adding the same listener many times

### ISSUE THREAD

**Issue by igorw** [igorw/evenement#7]
What would jesus/js do?

**Comment by WyriHaximus** [comment]
jesus/js would postpone this to `v3.0.0` not to turn this into a BC break

**Comment by WyriHaximus** [comment]
Been thinking about a good way to do this without a performance hit but can't come up with any. Unless there is a `spl_object_hash` alternative for `callable`s I'm closing this issue. And leave the responsibility for assigning the same listeners multiple times to the user.
