### ISSUE TITLE
PSR-14 compatibility

### ISSUE THREAD

**Issue by andrzejkupczyk** [igorw/evenement#73]
Do you plan to make this package compatible with PSR?

https://www.php-fig.org/psr/psr-14
https://github.com/php-fig/event-dispatcher
https://github.com/php-fig/event-dispatcher-util

**Comment by WyriHaximus** [comment]
there are currently no plans to do this. But it's about time to start thinking about v4 so maybe?

**Comment by andrzejkupczyk** [comment]
Definitely :+1: There are projects in which I would prefer to use this package instead of e.g. the Symfony EventDispatcher component but following the PSR is more important.

**Comment by WyriHaximus** [comment]
Been revisiting outstanding issues, and the pending release of this package. And while I get the drive to use a common standard, this package doesn't fit that standard. Not every event emitter should implement PSR-14, this is one of the cases where implementing it would do more harm then good for most users of this package.

**Comment by andrzejkupczyk** [comment]
Thank you for considering this!
