### ISSUE TITLE
Adding types to returns and arguments

### ISSUE THREAD

**Issue by MarcHagen** [igorw/evenement#87]
So this should be a major version, I guess, because it could break all installations.

However, 7.0 <> 7.4 is deprecated and it is a good thing to maybe move to `php: ^8.0` so we can add a little bit of strictness to the code.

What are your thoughts on this?

**Comment by ericsizemore** [comment]
@WyriHaximus this issue could be closed with #88 being merged.

**Comment by MarcHagen** [comment]
It seems this issue can be closed as the current dev branch has the typing. 
Will follow #90 for the release at one point.
